version: 2.1

executors:
  docker_executor:
    docker:
      - image: docker:19.03.12

commands:
  build_prometheus:
    steps:
      - setup_remote_docker
      - run:
          name: Verify docker is installed
          command: docker run hello-world
      - run:
          name: Verify environment is set up correctly
          command: |
            pwd
            ls -la
            echo $DISPLAY
            echo ${DISTRO_TAG}
            # Generate .Xauthority file.
            touch ~/.Xauthority
            cat ~/.Xauthority
      - run:
          name: Set up container and build prometheus
          command: |
            # Retrieve image.
            docker pull jdtaylor7/prometheus:latest-${DISTRO_TAG}
            # Create dummy container to hold volume.
            docker create -v /home/circleci --name configs jdtaylor7/prometheus:latest-${DISTRO_TAG} /bin/true
            # Copy Xauthority config into dummy volume.
            docker cp ~/.Xauthority configs:/home/circleci/.Xauthority
            # Run container and build prometheus.
            docker run -it --rm --network=host --volumes-from configs -e DISPLAY=$DISPLAY jdtaylor7/prometheus:latest-${DISTRO_TAG} /bin/sh -c " \
                cd prometheus && \
                ./build.sh -t -e prometheus"

jobs:
  build_archlinux:
    executor: docker_executor
    environment:
      - DISTRO_TAG: archlinux
    steps:
      - build_prometheus
  # build_ubuntu:
  #   executor: linux_executor
  #   steps:
  #     - build_prometheus

workflows:
  version: 2.1
  test_all:
    jobs:
      - build_archlinux
      # - build_ubuntu
