version: 2.1

commands:
  build_prometheus:
    steps:
      - checkout
      - run:
          name: Build prometheus
          command: |
            pwd
            ls -l
            uname -a
            cat /etc/*-release
            ./build.sh -t -e prometheus

jobs:
  build_archlinux:
    docker:
      - image: jdtaylor7/prometheus:latest-archlinux
    steps:
      - build_prometheus
  build_ubuntu:
    docker:
      - image: jdtaylor7/prometheus:latest-ubuntu
    steps:
      - build_prometheus

workflows:
  version: 2.1
  test_all:
    jobs:
      - build_archlinux
      - build_ubuntu
